### ISSUE TITLE
ffi memory pointer workaround

### ISSUE THREAD

**Issue by jsvd** [djberg96/win32-eventlog#14]
have you considered applying the workaround you proposed in https://github.com/jruby/jruby/issues/2293:

```ruby
if RUBY_PLATFORM == 'java' && ENV_JAVA['sun.arch.data.model'] == '64'
  :ulong_long
else
  :uintptr_t
end
```

so this library is usable in JRuby 64bit until the fix lands upstream?

**Comment by djberg96** [comment]
Let me check to see if they fixed this in pre2. If not, I'll add the fix.

**Comment by jsvd** [comment]
It is not fixed.

```
irb(main):006:0> RUBY_DESCRIPTION
=> "jruby 9.0.0.0.pre2 (2.2.2) 2015-04-28 2755ae0 Java HotSpot(TM) 64-Bit Server VM 25.31-b07 on 1.8.0_31-b13 +jit [Windows 7-amd64]"
irb(main):007:0> FFI::MemoryPointer.new(:uintptr_t).read_pointer
IndexError: Memory access offset=0 size=8 is out of bounds
        from org/jruby/ext/ffi/AbstractMemory.java:1922:in `read_pointer'
        from (irb):7:in `<eval>'
        from org/jruby/RubyKernel.java:1005:in `eval'
        from org/jruby/RubyKernel.java:1315:in `loop'
        from org/jruby/RubyKernel.java:1125:in `catch'
        from org/jruby/RubyKernel.java:1125:in `catch'
        from jirb:13:in `<top>'
```

**Comment by djberg96** [comment]
Ok, pushed out 0.6.3, thanks.

**Comment by jsvd** [comment]
@djberg96 I'm not sure what 66a128ab6369424babde765eebddbb4fc2021161 did but as long as there are calls to FFI::MemoryPointer.new(:uintptr_t) in the code it will still fail

**Comment by djberg96** [comment]
Well, that wasn't very thorough of me, was it. I think I accidentally ran the tests with a 32-bit JRuby.

I'll get that fixed today.

**Comment by djberg96** [comment]
Hm, having some problems getting my custom typedefs imported at the instance level. Gonna have to spend a bit more time on this than I thought.

**Comment by djberg96** [comment]
Hm, been thinking about this some more. I'm not sure how much more I want to integrate workarounds in my code for something that JRuby should fix. Let me see if I can get them to fix this in time for 9000.

**Comment by djberg96** [comment]
Ok, they found the bug and fixed it. The fix will be in the next release. I'm simply going to put a caveat in the README that you must use JRuby 9k or later.
