### ISSUE TITLE
[request] License change

### ISSUE THREAD

**Issue by jsvd** [djberg96/win32-eventlog#15]
Hi @djberg96 would you consider changing this project's license? We're hoping to use it in logstash eventlog input plugin :)

The pr is https://github.com/logstash-plugins/logstash-input-eventlog/pull/21

I don't understand anything about licenses, not sure how compatible Artistic 2.0 is with the ones that we accept right now: https://github.com/elastic/logstash/blob/master/spec/license_spec.rb#L12-L16

Does this conflict with your views on the licensing of this library? Thanks in advance!

**Comment by djberg96** [comment]
@jsvd I've thought about changing the license to Apache 2.0. I don't think it will be an issue, but let me run it past the other contributor(s).

**Comment by jsvd** [comment]
any update @djberg96 ?

**Comment by djberg96** [comment]
@jsvd I've posted on our google group. I'm awaiting feedback to see what others think.

**Comment by jsvd** [comment]
@djberg96 alright thanks !

**Comment by jsvd** [comment]
Hi @djberg96, any update on this?

**Comment by djberg96** [comment]
@jsvd I think it's going to stay at Artistic 2.0 for now. It is compatibile with the GPL (according to http://www.gnu.org/licenses/license-list.en.html) so I've no immediate plans to change it.

**Comment by jsvd** [comment]
Ok, thank you.
