### ISSUE TITLE
exception due to method nstrip called on a FFI::MemoryPointer object

### ISSUE THREAD

**Issue by jsvd** [djberg96/win32-eventlog#16]
I'm getting the following exception:

```
Error: undefined method `nstrip' for #<FFI::MemoryPointer address=0x3f9aa0 size=8192> 
```

This is because of [this code](https://github.com/djberg96/win32-eventlog/blob/ffi2/lib/win32/eventlog.rb#L1018-L1022):

```ruby
                  break if buf.nstrip != ""
                end
              }

              va = va.gsub("%%#{x.first}", buf.nstrip)
```

where buf.nstrip is called, however, we can see that buf is created as such:
`buf = FFI::MemoryPointer.new(EVENTLOGRECORD, needed)`

And `FFI::MemoryPointer` does not have `nstrip`. Looking at old commits, it seems that `buf` used to be a string.

**Comment by jsvd** [comment]
My guess at a patch would be to do `buf.read_string.nstrip`

**Comment by djberg96** [comment]
@jsvd, can you try buf.read_string.nstrip, and make sure that works? If so, I'll get a patch in asap.

**Comment by jsvd** [comment]
I haven't been yet able to replicate this. the code seems to trigger when getting the User from the event, but this seems to be hard/impossible to fake in powershell

**Comment by jsvd** [comment]
@djberg96 actually the nstrip method no longer exists in the ffi2 branch, so should this be implemented in another way or does this method need to be added again?

**Comment by djberg96** [comment]
@jsvd Oops. I think it should just be replaced with read_string.

**Comment by jsvd** [comment]
I was able to replicate this consistently by stopping and starting security essentials realtime protection. example:

```xml
Log Name:      System
Source:        Microsoft Antimalware
Date:          29-10-2015 14:28:39
Event ID:      5001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Jsvd-VAIO
Description:
Microsoft Antimalware Real-time Protection scanning for malware and other potentially unwanted software was disabled.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft Antimalware" />
    <EventID Qualifiers="0">5001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-10-29T14:28:39.000000000Z" />
    <EventRecordID>577683</EventRecordID>
    <Channel>System</Channel>
    <Computer>Jsvd-VAIO</Computer>
    <Security />
  </System>
  <EventData>
    <Data>%%860</Data>
    <Data>4.6.0305.0</Data>
  </EventData>
</Event>
```

**Comment by djberg96** [comment]
@jsvd Did replacing .nstrip with .read_string work?

**Comment by jsvd** [comment]
yes it no longer crashes :+1:


`#<struct Struct::EventLogStruct record_number=577696, time_generated=2015-10-2914:42:34 +0000, time_written=2015-10-29 14:42:34 +0000, event_id=7036, event_type="information", category=0, source="Service Control Manager", computer="Jsvd-VAIO", user=nil, string_inserts=["Multimedia Class Scheduler", "running"], description="The Multimedia Class Scheduler service entered the running state.\r\n">`

**Comment by djberg96** [comment]
@jsvd excellent, I'll have a patch out shortly.

**Comment by djberg96** [comment]
Ok, pushed out 0.6.5 just now. Thanks for the report!
