### ISSUE TITLE
windows compatibility list

### ISSUE THREAD

**Issue by jsvd** [djberg96/win32-eventlog#17]
hi, do you know which versions of windows this library is compatible with?

looking at #12 it seems windows xp 32bit isn't (but could be), any other known incompatibility?

**Comment by djberg96** [comment]
@jsvd Basically I support whatever MS supports. If it happens to work on older versions, great, but don't count on it.

**Comment by jsvd** [comment]
Sorry, I guess I phrased my question badly: I'd like to know how to find which windows versions implement the apis used in this gem.

**Comment by acchen97** [comment]
In particular, I'm wondering what Windows Server versions this supports.  Any idea?

**Comment by djberg96** [comment]
@acchen97 It's running against 2012 on Appveyor, and it passes on Windows 7 and 8.

**Comment by acchen97** [comment]
@djberg96 very helpful, thank you! :)
