### ISSUE TITLE
Pointer argument error in win32_eventlog

### ISSUE THREAD

**Issue by TheR2** [djberg96/win32-eventlog#18]
I have just recently updated from ruby 2.0 to ruby 2.2. and I got this error when reading windows log files:
":pointer argument is not a valid pointer\n"
"//skupni/d$/OZS/Informacijska_podpora/ruby22/lib/ruby/gems/2.2.0/gems/win32-eventlog-0.6.4/lib/win32/eventlog.rb:1043:in `FormatMessage'"
"//skupni/d$/OZS/Informacijska_podpora/ruby22/lib/ruby/gems/2.2.0/gems/win32-eventlog-0.6.4/lib/win32/eventlog.rb:1043:in `block in get_description'"
"//skupni/d$/OZS/Informacijska_podpora/ruby22/lib/ruby/gems/2.2.0/gems/win32-eventlog-0.6.4/lib/win32/eventlog.rb:1033:in `each'"
"//skupni/d$/OZS/Informacijska_podpora/ruby22/lib/ruby/gems/2.2.0/gems/win32-eventlog-0.6.4/lib/win32/eventlog.rb:1033:in `get_description'"
"//skupni/d$/OZS/Informacijska_podpora/ruby22/lib/ruby/gems/2.2.0/gems/win32-eventlog-0.6.4/lib/win32/eventlog.rb:576:in `read'"

Here is the code. Error happens in second line.
windows_log = Win32::EventLog.open(log)
windows_log.read(Win32::EventLog::BACKWARDS_READ | Win32::EventLog::SEQUENTIAL_READ) do |events| 
....

I can confirm that error is present from version 0.6.0 and up. Version 0.5.3. works as expected.

by
TheR

**Comment by djberg96** [comment]
@TheR2 That's curious. Can you find the corresponding entry in your eventlog and paste it? Also, what codepage are you using?

The pointer in question is declared like so:

    buf  = FFI::MemoryPointer.new(:char, 8192)

Is it possible you've exceeded that buffer size? I can increase it if necessary.

**Comment by djberg96** [comment]
Was thinking about this again, and I don't think it's a buffer issue. I did notice that if the first `FormatMessage` fails the original buffer is never cleared. I modified it so that if there's a failure then the second call to `FormatMessage` gets a fresh pointer.

**Comment by djberg96** [comment]
@TheR2 I added `buf.clear` in that second block to see if that would fix it. Can you check?

**Comment by djberg96** [comment]
No followup, so closing.
